### ISSUE TITLE
Suggestions Needed

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/genialkartik.github.io#1]
Please, go to my personal website and suggest me whatever you like.

**Comment by ChiefMikeK** [comment]
1. your site;
> http://kartiktyagi.me/ ...Kindly, drop an Email in case of any query.   

😕 ¿No Email? ___obfuscated or not___ link 2b found. 😖 

****
2.  https://github.com/mozilla/mozillians/issues/3947
:neckbeard:  was trying to invite You@ mozillians.org

**Comment by genialkartik** [comment]
Thank @ChiefMikeK for your concern. 
I've fixed the same. You can proceed with the mention/invitation.

**Comment by ChiefMikeK** [comment]
[bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1586610)

**Comment by genialkartik** [comment]
I would recommend you to visit this [Bug #1585611](https://bugzilla.mozilla.org/show_bug.cgi?id=1585611) also.
