### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/genialkartik.github.io#4]
#enhance
#find_bug
#contribute

**Comment by MaleeshaKumarage** [comment]
Its better if you can use CDN for the images.It will help to reduce the loading time.

**Comment by pilgrim-1610** [comment]
I recommend implementing bootstrap or w3.css to make the code much more compact and compatible for mobile devices

**Comment by sparkingdark** [comment]
let's check it
